import Head from "next/head";
import Hero from "../components/Hero";
import Categories from "../components/Categories";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Things To Do In Kansas City</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Categories />
    </div>
  );
}
